# Generated by Django 3.2.15 on 2022-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=64)),
                ('course_code', models.CharField(max_length=64)),
                ('seat_quota', models.IntegerField()),
            ],
        ),
    ]
