name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Django unit tests
        run: |
          pip3 install --user -r requirements.txt
          pip3 install coverage
          python3 ./demo/manage.py makemigrations
          python3 ./demo/manage.py migrate
          coverage run ./demo/manage.py test course login 
          coverage report -m